target("ArchVizRuntime", function ()
    set_kind("static")
    add_includedirs("$(projectdir)/engine/src", {public = true})
    add_includedirs("$(projectdir)/engine/3rd_party/json11", {public = true})
    add_headerfiles("**.h")
    add_files("**.cpp")
    add_packages("json11", {public = true})
    add_packages("spdlog", {public = true})
    add_packages("eigen", {public = true})
    after_build(function (target)
        import("core.project.config")
        os.mkdir("$(projectdir)/bin")

        local targetfile = target:targetfile()
        print("build %s", targetfile)

        print("start copy assets")

        os.rm("$(projectdir)/bin/*.ini")
        os.cp("$(projectdir)/data/*.ini", "$(projectdir)/bin")
        os.rm("$(projectdir)/bin/asset-test")
        os.cp("$(projectdir)/data/asset-test", "$(projectdir)/bin")
        os.rm("$(projectdir)/bin/config")
        os.cp("$(projectdir)/data/config", "$(projectdir)/bin")
        os.rm("$(projectdir)/bin/shader")
        os.cp("$(projectdir)/data/shader", "$(projectdir)/bin")

        print("finish copy assets")
    end)
end)
