target("test", function ()
    set_kind("binary")
    add_files("main.cpp")
    -- add_deps("ArchVizRuntime")
    after_build(function (target)
        import("core.project.config")
        local targetfile = target:targetfile()
        os.mkdir("$(projectdir)/bin")
        os.cp(targetfile, path.join("$(projectdir)/bin", path.filename(targetfile)))
        print("build %s", targetfile)
    end)
end)
